### ISSUE TITLE
any swift support?

### ISSUE THREAD

**Issue by galileomd** [50ButtonsEach/fliclib-ios#1]
any help building into a swift project?

**Comment by galileomd** [comment]
On Xcode 7.  I've tried creating a test project, added the framework, turned on the "Allow non-modular includes in framework module" to Yes, and started creating a bridging header.

importing with #import <fliclib/fliclib.h> gives me an error "Could not build module fliclib".

any ideas?

**Comment by AntonMeier** [comment]
Yes, we will look in to this. I believe I know what the issue is about. I will update you more on this tomorrow. Also, we will put up a tutorial for Swift also soon, but I am not sure if it will go up this week or next.
Hope you can be patient!

**Comment by galileomd** [comment]
absolutely, thanks for the update and looking forward to testing out the hardware!

**Comment by AntonMeier** [comment]
Since I promised to answer today I'll do that. I made some updates to fix the issues that you saw and also verified that everything works as it should now. Thank you for giving me the heads up, we sort of forgot to test the latest commit with Swift. I will commit and push the updated version as soon as possible. I'll let you know!

**Comment by AntonMeier** [comment]
Hi again, I have now pushed a new release that works with swift. What you need to to in order to get it working is to create a bridging_header in your project that imports the fliclib/fliclib.h file. A tutorial for this will be available soon.

**Comment by galileomd** [comment]
awesome got it working without issues!  i just followed this tutorial:
 http://www.learnswiftonline.com/getting-started/adding-swift-bridging-header/
