### ISSUE TITLE
Can't restore flic buttons after uninstalling and reinstaling my app

### ISSUE THREAD

**Issue by youss-cs** [50ButtonsEach/fliclib-ios#11]
Hi,

When my app is suspended or terminated i can restore my flic buttons in "flicManagerDidRestoreState(manager: SCLFlicManager)" with manager.knownButtons() function.

but when i uninstall and reinstall my app i can't restore them in my app. Any solution ?

**Comment by AntonMeier** [comment]
Actually this is not a bug. On iOS if you uninstall an application you also delete all of that apps data storage. We don't have a solution for this at the moment, and I honestly think it is not a big problem since users don't usually uninstall apps that they intend to continue using.
