### ISSUE TITLE
Update iOS tutorial regarding latest changes

### ISSUE THREAD

**Issue by dukhanov** [50ButtonsEach/fliclib-ios#13]
Hello,

I have downloaded the latest version of the Flic sdk, and methods and interfaces do not match with SDK documentation: https://flic.io/partners/developers/documentation/ios/index.html
https://flic.io/partners/developers/ios-tutorial

**Comment by AntonMeier** [comment]
yes, it is on our todo list!

**Comment by dukhanov** [comment]
Thanks
