### ISSUE TITLE
Bot example

### ISSUE THREAD

**Issue by SharadExt** [50ButtonsEach/fliclib-ios#15]
Hi, 
I dont know how to integrate bot in our iOS app . Can anybody help me?

**Comment by AntonMeier** [comment]
Can you please explain what you mean with "bot" ?

**Comment by SharadExt** [comment]
Do you know skype bot ?

**Comment by SharadExt** [comment]
check this https://en.wikipedia.org/wiki/Internet_bot

**Comment by SharadExt** [comment]
I want to integrate this in my own app.

**Comment by fabianbergmark** [comment]
How is this related to the Flic SDK?

**Comment by SharadExt** [comment]
No it is not related to the flic SDK. 
But if I get solution then I can integrate bot with flic device

**Comment by SharadExt** [comment]
Just tell me  procedure or steps .

**Comment by fabianbergmark** [comment]
To implement a bot? We do not program for your

**Comment by AntonMeier** [comment]
I am sorry but we can not help you with this. This is not in our area of expertise. Furthermore, you need to know what kind of bot you want to make.

**Comment by SharadExt** [comment]
Ok no problem
