### ISSUE TITLE
Double click event never happens

### ISSUE THREAD

**Issue by dukhanov** [50ButtonsEach/fliclib-ios#17]
I am trying to subscribe to a double click event,
But a double click event never happens.
I've forked your repository, and added subscribers to events

```
- buttonClick
- buttonDoubleClick
- buttonHold
```

`buttonClick` event is happened
`buttonHold`event is happened

but 
`buttonDoubleClick`never is happened

If I double click on flic, I received two `buttonClick` events instead one `buttonDoubleClick` event

Could you tell me what am I doing wrong?

https://github.com/dukhanov/ios-boilerplate-objc/commit/5288d40690ef7f9e26a20dd0cfaa1c638069d7a8

**Comment by AntonMeier** [comment]
You need to set the triggerBehavior property of the button to SCLFlicButtonTriggerBehaviorClickAndDoubleClickAndHold

**Comment by dukhanov** [comment]
Thanks it helped.

If I understood correctly, I need to set triggerBehavior property of the button in `didGrabFlicButton` method. Is it correct?

**Comment by AntonMeier** [comment]
yes, that is correct. You can all the button configuration in the didGrabFlicButton callback since the settings will be remembered.
