### ISSUE TITLE
Cannot build in Xcode due to improperly matched HTML tags

### ISSUE THREAD

**Issue by madisonscott** [50ButtonsEach/fliclib-ios#18]
Framework fails to build in Xcode 7.3 due to improperly matched `<code>` HTML tags in Headers/SCLFlicManager.h on lines 102 and 169.

**Comment by AntonMeier** [comment]
Yes, thanks... That is very strange.. I don't know how that sneaked in there.. But you should still be able to run the framework regardless. I will update this as soon as possible!

**Comment by madisonscott** [comment]
Thank you!
