### ISSUE TITLE
didGrabFlicButton never called

### ISSUE THREAD

**Issue by madisonscott** [50ButtonsEach/fliclib-ios#19]
Hi all, after following both the iOS integration tutorial and the example Objective C project, I still cannot get my app to grab the button. I'm taken to the Flic app and can select the button and am properly redirected back to my app, but the didGrabFlicButton method is never called. Has anyone experienced this issue before and would know anything about why it might be occurring?

**Comment by madisonscott** [comment]
Had to put the openUrl method in the pre-existing AppDelegate, nevermind!

**Comment by arlomedia** [comment]
To be clear, it looks like didGrabFlicButton is not called automatically. You have to call it yourself from openURL -- something like this:

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
	if ([url.absoluteString containsString:@"flicWasGrabbed"]) {
		return [[SCLFlicManager sharedManager] handleOpenURL:url];
	}
}
```
