### ISSUE TITLE
Add a field "event datetime" for the Button

### ISSUE THREAD

**Issue by dukhanov** [50ButtonsEach/fliclib-ios#20]
For example, in case of Bluetooth is disabled, and I click the Flic, then I turn Bluetooth on and I will immediately receive an event (Flic was clicked `didReceiveButtonClick`), but I don't know exactly time when Flic was clicked.

Is it possible to add event date-time field (when Fic was clicked) for the Flic button?

**Comment by Emill** [comment]
The age parameter for didReceiveButtonClick contains the number of seconds ago the button was pressed.

**Comment by dukhanov** [comment]
That's what I was looking for.
Thanks.
