### ISSUE TITLE
fliclib.framework with White Label Framework in 1 Project

### ISSUE THREAD

**Issue by lvandyk** [50ButtonsEach/fliclib-ios#21]
We have an iOS app that is using the fliclib.framework perfectly. We also now have the white label framework that you have provided us. We want to use both in our project so users can use both the normal flic buttons as well as our white label ones.

Is this possible or will I encounter issues?

**Comment by lvandyk** [comment]
I have managed to import both frameworks into the project and build it. Will post update if I get it working.

**Comment by jacquesvanzyl** [comment]
You can use the `[[SCLFlickManager sharedManager] grabFlicFromFlicAppWithCallbackUrlScheme:appUrl];`  method to open up the Flic app which allows you to choose the Flic button. You also have to add to your AppDelegate.m: 
`- (BOOL)application:(UIApplication *)application openURL:(nonnull NSURL *)url sourceApplication:(nullable NSString *)sourceApplication annotation:(nonnull id)annotation {
    return [[BluetoothManager sharedManager] handleOpenUrl:appUrl];
}`

So you are using the same delegate that you are for the white labeled framework.

And follow the instructions on the partners SDK to edit your info.plist NOTE: don't include the partners framework as your poic framework has the required methods as well.
