### ISSUE TITLE
didReceiveButtonDoubleClick:queued:age not called

### ISSUE THREAD

**Issue by hansemannn** [50ButtonsEach/fliclib-ios#24]
Hey guys,

I'm the vendor of [Ti.Flic](https://github.com/hansemannn/ti.flic), a native module for the Appcelerator Titanium framework. All works fine so far (connecting, getting clicks and button-down/ups), except that the double-clicks are not fired. 

The used Flic button is "Siyou Flic" (green) and everything looks correct on the module's side.

**Comment by AntonMeier** [comment]
look in the documentation/button header file for triggerBehavior. You have to select the proper mode.

**Comment by hansemannn** [comment]
Makes sense, thank you!

**Comment by hansemannn** [comment]
One sec. I only can see the `triggerBehavior` in the flic button itself, is it writable? **EDIT**, yeah, looks like. cool!
