### ISSUE TITLE
Minimum Target is iOS 8

### ISSUE THREAD

**Issue by tommy1005** [50ButtonsEach/fliclib-ios#25]
Hello Flic iOS-Team,

i added Flic support (API 1.1.11) to my iOS app "Chillout Control". I released a new version a few days ago with compatibility starting at iOS 5.1.1 until iOS 10.2.
**Now your framework requires a minimum of iOS 8.0**

Is it possible to include/link your framework (also with 5.1.1) and just invoke/use it on iOS >= 8.0?
 
> Linker command failed:
> embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/fliclib.framework/fliclib) for architecture arm64

_I hope it does not look the same with the Android Library_

Regards,
Thomas Kirschner

Chillout Control iOS App:
[https://itunes.apple.com/de/app/chillout-control/id429895993?mt=8](https://itunes.apple.com/de/app/chillout-control/id429895993?mt=8)

**Comment by fabianbergmark** [comment]
The Android library has a minimum SDK version of 19, as it requires the Flic Android app to be installed, which has the minimum SDK version 19.

**Comment by hansemannn** [comment]
The Flic iOS app also required iOS 8.1, so I think that will cause the main problem. You *could* change the framework to not embed the lib and instead link it manually, but you rather want to bump your minimum supported version. According to [the AppStore statistics](https://developer.apple.com/support/app-store/), 94 % of the devices nowadays running iOS 9 or later.

**Comment by tommy1005** [comment]
Thank you for the answer @hansemann 😉 Manual linking of the flic framework doesn't work. This causes the problem described in this issue.
I think it would work linking a static library (compiled framework). But i will upgrade the project to iOS 8 (and my iPad1 will keep stuck in the old app version).
