### ISSUE TITLE
grabFlicFromFlicApp opens store instead flic app

### ISSUE THREAD

**Issue by janonymus** [50ButtonsEach/fliclib-ios#26]
Hi!

I'm not sure if I did everything correctly, but I had followed everything that the tutorial offered, and when I fire **grabFlicFromFlicApp** then it opens the app store at the flic app (I have already installed this app, and have used the button there)

**Comment by janonymus** [comment]
found the issue...

LSApplicationQueriesSchemes must be an array type (somehow it was a dict)

**Comment by arlomedia** [comment]
And the LSApplicationQueriesSchemes list must contain "flic20". I didn't see this in the text of the tutorial, but it's shown in one of the screen shots.
