### ISSUE TITLE
React Native Integration

### ISSUE THREAD

**Issue by jdegger** [50ButtonsEach/fliclib-ios#34]
Could anybody point me in the right direction implementing the Flic SDK in combination with React Native? I have been looking into this and have had no luck so far.

Did anybody achieve this and if so, are there any examples available?

**Comment by mdfalcon104** [comment]
Did you try to build a bridge native code class? Does it work?

**Comment by jdegger** [comment]
Hi @dlpigpen, we found the following repository:

https://github.com/mdahiemstra/react-native-flic 
This one is focussed on the business buttons of Flic. Normal Flic buttons do not work with this.

We asked the creator of that plugin to work with us on a new plugin for non PBF (non business) buttons. We are still in the process of finishing this. The iOS version has a working prototype right now (implemented in our application too).

We let the creator know we are fine by releasing the new plugin as an open source project for others too. Hoping this incentives others to improve the plugin. 

Check out the following repositories:
https://github.com/mdahiemstra/react-native-flic-nonpbf
https://github.com/mdahiemstra/react-native-flic-nonpbf-example

**Comment by jdegger** [comment]
For anybody still looking into this: Flic2 for React Native is available through https://github.com/X-Guard/react-native-flic2/
