### ISSUE TITLE
Couldn't find a license for fliclib-ios

### ISSUE THREAD

**Issue by ImpactForgeCloud** [50ButtonsEach/fliclib-ios#35]
Hello

Couldn't find a license for fliclib-ios. Could you please add one?
If possible a simple and permissive one.
Because in this way people wouldn't be taking a legal risk by using fliclib in custom apps.

Thank you, Jose.

**Comment by AntonMeier** [comment]
You are correct. I have updated this. See README.md for more information. Please let me know if you have any further comments.
