### ISSUE TITLE
Old 'startScan & stopScan' methods

### ISSUE THREAD

**Issue by JValderramaN** [50ButtonsEach/fliclib-ios#40]
Hello, first thanks for supporting this library, thanks

I have a project with the library when using manager methods:

SCLFlicManager.startScan
SCLFlicManager.stopScan

Now I want to implement the new version, including the fix for Xcode 11.4 (xcframework), but these methods were removed, I did not find the commit (sorry if it was a novice), so I would like to know if these methods are no longer necessary, or how it is the new handling?

Best regards

**Comment by JValderramaN** [comment]
Hi, hope all is good!

please any suggest about this thread?

@AntonMeier

**Comment by AntonMeier** [comment]
Hello, I am confused. We have never had any startScan or stopScan on this framework. 

I am guessing that you are either referring to PbF (which is not publicly available on GitHub), or flic2lib (separate repository), which is the framework for the Gen. 2 Flic.

Can you confirm?

**Comment by JValderramaN** [comment]
Hi, thanks replying

I cannot find the specific version, but please take a look to the attached fliclib.framework which includes the SCLFlicPoicManager.h header, there is the methods: 'stopScan' and 'startScan'.

I don't know if I'm missing something, thanks for all help!

**Comment by AntonMeier** [comment]
The framework that you linked is not a public release. If is our "PbF" version for corporate use only. If you were sent this framework from someone at Flic then please reach out to that person and they will provide you with an up-to-date version. The version you linked is from 2017, so it is quite old. 

Please remove the download link from your comment.

**Comment by JValderramaN** [comment]
Thanks for all info!
Let's assume this is closed
