### ISSUE TITLE
Flic Grabber won't let me select any of my buttons

### ISSUE THREAD

**Issue by a-huy** [50ButtonsEach/fliclib-ios#5]
I'm trying to integrate Flic into my iOS project using your tutorial. I got to the point where I was trying to add a button to to Flic Manager, but none of them were available to select and I got an error alert (pictures attached). Why is this happening?

Any advice or help would be appreciated.

![img_0474](https://cloud.githubusercontent.com/assets/591548/11358841/2f3ab8de-922b-11e5-8b90-545fdf258c98.PNG)

**Comment by AntonMeier** [comment]
Sorry for the delayed response. Please contact our support team at support@shortcutlabs.com and they will help you out.. It is actually not a problem with the fliclib itself, but rather an issue with those buttons that you have. Sorry for the inconvenience.

**Comment by mph070770** [comment]
Does this problem mean I need new flic buttons?
