### ISSUE TITLE
errors when attempting to archive IPA

### ISSUE THREAD

**Issue by swangy** [50ButtonsEach/fliclib-ios#6]
Hi, i have bitcode enabled in my build settings but when trying to archive the app into an IPA i get 

ld: bitcode bundle could not be generated because '/GitHub/app/fliclib.framework/fliclib' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any suggestions?  was the framework built without full bitcode?

**Comment by AntonMeier** [comment]
Hello, thanks for the info, I will look in to it when I build the next version of Fliclib within the next week or so. There will be a lot of improvements in the next version.

**Comment by AntonMeier** [comment]
This should be fixed in 0.9.5. Let me know if you have any further issues.
