### ISSUE TITLE
error connecting to button since fliclib update?

### ISSUE THREAD

**Issue by galileomd** [50ButtonsEach/fliclib-ios#7]
Hi, having issues with connecting to the button recently since the lib update.. getting this error on delegate call to flicbutton(button, didFailToConnectWithError)...

> Error Domain=com.shortcutlabs.fliclib Code=10 "The operation couldn’t be completed. (com.shortcutlabs.fliclib error 10

any suggestions?

**Comment by galileomd** [comment]
actually the issue appears to be REconnecting to the app once connection is lost - flicManagerDidRestoreState is not called again once the flic is disconnected, ie when the button is out of range.  (although the flic app responds)  a manual reconnection is needed re-establish connection with the flic app.

**Comment by AntonMeier** [comment]
Hi,
We are aware of this, but thank you for submitting it! For the next release of fliclib-ios we have done a lot of rework on the connectivity to make it more reliable, as well as fixing some bugs, such as the one mentioned. We have also added better error handling, changed flicmodes, etc. 

I don't yet have an ETA on when we will release it, but it shouldn't be too long. We also have to release a new Flic app to the app store for that as well as a firmware upgrade.

/Anton

**Comment by AntonMeier** [comment]
This should be solved in 0.9.5 combined with the new version of the Flic App, which is pending to the App Store as we speak.
